# -*- coding: utf-8 -*-
"""CIE=1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZHUsh9scpWbbRbLuI0xm0wURG7CzD9gz
"""

import pandas as pd
s_a=[1,2,3,4,5]
s_b=[2,4,6,8,10]
set1=set(s_a)
set2=set(s_b)
insert=set1.intersection(set2)
ans=list(insert)
ans

import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv("mtcars.csv")
df

plt.hist(df['mpg'],bins=10,edgecolor="black")
plt.title("Histogram")
plt.xlabel("mpg")
plt.ylabel("frequency")
plt.show()

plt.scatter(df["wt"],df["mpg"],color="red")
plt.title("scatter plot")
plt.xlabel("weight")
plt.ylabel("mpg")
plt.show()

transmission_counts=df["am"].value_counts()
transmission_counts.plot(kind="bar",color="red")
plt.title("Bar plot")
plt.xlabel("transmission type (0=automatic,1=manual)")
plt.ylabel("frequency")
plt.show()

plt.boxplot(df["mpg"],vert=False)
plt.title("box plot")
plt.xlabel("mpg")
plt.show()